import LeanC2.Analytic.GenuineBulkConcrete

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_atOne
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_atOne

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_residualBound
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_residualBound

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_centralDefectBound
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_centralDefectBound

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_separatedCentralBounds
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_separatedCentralBounds

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_pointwiseOscillatoryResidualBound
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_pointwiseOscillatoryResidualBound

#check C2.offCriticalStripNonvanishing_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_exponentialResidualBound
#check C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle_of_exponentialResidualBound

#print C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle
#print axioms C2.mathlibRiemannHypothesis_of_continuationAndOddTailBalancingAntiMiracleMiddle

