import LeanC2.AuditContinuedQuartetPositiveBoxGenuineOdd

/-!
# Positive-box odd-reference bridge audit

ROUTE_TAG: AUDIT_SHIM
ROUTE_TAG: OPTIONAL_REFINEMENT

This file connects the abstract odd-reference ledger to a matching abstract
bulk model and a conditional comparison with the complete genuine object.
-/

namespace C2
namespace ContinuedQuartetAudit

noncomputable section

/-- Central target generated by an abstract odd reference. -/
noncomputable def positiveBoxOddRefCentral
    (oddRef : ℂ → ℂ) : ℂ → ℂ :=
  centralFromOddChannel oddRef

/-- Positive-box anchor generated by an abstract odd reference. -/
noncomputable def positiveBoxOddRefAnchor
    (oddRef : ℂ → ℂ) : ℂ → ℂ :=
  fun s => verticalDepthTailFromTwo s - positiveBoxOddRefCentral oddRef s

/-- Positive-box rectangular cutoff vector generated by an abstract odd reference. -/
noncomputable def positiveBoxOddRefCutVec
    (oddRef : ℂ → ℂ) (K M : ℕ) : ℂ → ℂ :=
  fun s => rectangularGenuine s K M - positiveBoxOddRefCentral oddRef s

/-- Vertical residual split generated by an abstract odd reference. -/
noncomputable def positiveBoxOddRefVSplit
    (oddRef : ℂ → ℂ) (K M : ℕ) : ℂ → ℂ :=
  fun s => positiveBoxOddRefAnchor oddRef s +
    positiveBoxOddRefCutVec oddRef K M s

/-- Vertical residual used by the abstract odd-reference bulk model. -/
noncomputable def positiveBoxOddRefVerticalResidual
    (oddRef : ℂ → ℂ) (K M : ℕ) : ℂ → ℂ :=
  fun s =>
    verticalDepthTailFromTwo s +
      rectangularGenuine s K M -
      (2 : ℂ) * positiveBoxOddRefCentral oddRef s

theorem positiveBoxOddRefVerticalResidual_eq_vSplit
    (oddRef : ℂ → ℂ) (K M : ℕ) (s : ℂ) :
    positiveBoxOddRefVerticalResidual oddRef K M s =
      positiveBoxOddRefVSplit oddRef K M s := by
  unfold positiveBoxOddRefVerticalResidual positiveBoxOddRefVSplit
    positiveBoxOddRefAnchor positiveBoxOddRefCutVec
  ring

/-- Cutoff error against the abstract odd-reference central target. -/
theorem positiveBoxOddRefCutVec_eq_cutoffError
    (oddRef : ℂ → ℂ) (K M : ℕ) (s : ℂ) :
    positiveBoxOddRefCutVec oddRef K M s =
      c2ConcreteCutoffErrorFromTarget
        (positiveBoxOddRefCentral oddRef) K M s := by
  unfold positiveBoxOddRefCutVec c2ConcreteCutoffErrorFromTarget
    c2RectangularGenuineOperator
  rfl

/-- Abstract odd-reference balancing seed for the positive-box audit model. -/
noncomputable def positiveBoxOddRefBalancingSeed
    (oddRef : ℂ → ℂ) (N K M : ℕ) : ℂ → ℂ :=
  fun s =>
    (-positiveBoxOddRefVerticalResidual oddRef K M s -
      c2HorizontalRegularizedDefect
        (oddRefHorizontalLayerDefect oddRef N) s) *
      (1 - q s)

/-- Bulk model generated by the abstract odd-reference central target. -/
noncomputable def positiveBoxOddRefBulkModel
    (oddRef : ℂ → ℂ) (N K M : ℕ) : ℂ → ℂ :=
  c2AnalyticBulkF
    (c2BulkGdelta
      (c2TiltRegularizedResidual
        (c2SeededTiltLayerResidual
          (positiveBoxOddRefBalancingSeed oddRef N K M)))
      (c2HorizontalRegularizedDefect
        (oddRefHorizontalLayerDefect oddRef N)))
    (c2BulkEdelta
      (c2ConcreteCutoffErrorFromTarget
        (positiveBoxOddRefCentral oddRef) K M))

/-- Expanded form of the abstract odd-reference bulk model. -/
theorem positiveBoxOddRefBulkModel_eq_expanded
    (oddRef : ℂ → ℂ) (N K M : ℕ) (s : ℂ) :
    positiveBoxOddRefBulkModel oddRef N K M s =
      verticalDepthTailFromTwo s +
        c2TiltRegularizedResidual
          (c2SeededTiltLayerResidual
            (positiveBoxOddRefBalancingSeed oddRef N K M)) s +
        c2HorizontalRegularizedDefect
          (oddRefHorizontalLayerDefect oddRef N) s +
        c2ConcreteCutoffErrorFromTarget
          (positiveBoxOddRefCentral oddRef) K M s := by
  unfold positiveBoxOddRefBulkModel c2AnalyticBulkF
    c2BulkGdelta c2BulkEdelta
  ring

/-- The odd-reference seed cancels its paired vertical and horizontal residuals. -/
theorem positiveBoxOddRefRegularizedResidual_balancingSeed
    (oddRef : ℂ → ℂ) (N K M : ℕ) {s : ℂ} (hs : 0 < s.re) :
    c2TiltRegularizedResidual
        (c2SeededTiltLayerResidual
          (positiveBoxOddRefBalancingSeed oddRef N K M)) s =
      -positiveBoxOddRefVerticalResidual oddRef K M s -
        c2HorizontalRegularizedDefect
          (oddRefHorizontalLayerDefect oddRef N) s := by
  have hden : 1 - q s ≠ 0 := by
    simpa [q] using verticalResolvent_den_ne_zero_of_re_pos s hs
  unfold positiveBoxOddRefBalancingSeed
  rw [c2SeededTiltRegularized_eq_resolvent _ hs]
  rw [mul_assoc, mul_inv_cancel₀ hden]
  ring

/-- The abstract odd-reference bulk model closes on its central target. -/
theorem positiveBoxOddRefBulkModel_eq_central_of_re_pos
    (oddRef : ℂ → ℂ) (N K M : ℕ) {s : ℂ} (hs : 0 < s.re) :
    positiveBoxOddRefBulkModel oddRef N K M s =
      positiveBoxOddRefCentral oddRef s := by
  rw [positiveBoxOddRefBulkModel_eq_expanded]
  rw [positiveBoxOddRefRegularizedResidual_balancingSeed
    oddRef N K M hs]
  unfold positiveBoxOddRefVerticalResidual
    c2ConcreteCutoffErrorFromTarget c2RectangularGenuineOperator
  ring

/--
Compatibility between an abstract odd reference and the genuine central object
on the selected box.
-/
structure PositiveBoxOddRefCompatibility
    (data : GenuineOddContinuationData) : Prop where
  central_compat :
    ∀ ⦃s : ℂ⦄, s ∈ positiveBox →
      positiveBoxOddRefCentral data.oddRef s = genuineFInfinite s

/-- The odd-reference bulk model matches the genuine object on the box. -/
theorem positiveBoxOddRefBulkModel_eq_genuine_of_compat
    {data : GenuineOddContinuationData}
    (compat : PositiveBoxOddRefCompatibility data)
    {s : ℂ} (hs : s ∈ positiveBox) :
    positiveBoxOddRefBulkModel
        data.oddRef positiveBoxN positiveBoxK positiveBoxM s =
      genuineFInfinite s := by
  calc
    positiveBoxOddRefBulkModel
        data.oddRef positiveBoxN positiveBoxK positiveBoxM s =
      positiveBoxOddRefCentral data.oddRef s :=
        positiveBoxOddRefBulkModel_eq_central_of_re_pos
          data.oddRef positiveBoxN positiveBoxK positiveBoxM
          (positiveBox_re_pos hs)
    _ = genuineFInfinite s :=
        compat.central_compat hs

/-- Analytic bounds for the abstract odd-reference bridge. -/
structure PositiveBoxOddRefBridgeBounds
    (data : GenuineOddContinuationData) : Prop where
  truncation : PositiveBoxOddRefTruncationData data.oddRef
  anchor_bound :
    ∀ ⦃s : ℂ⦄, s ∈ positiveBox →
      ‖positiveBoxOddRefAnchor data.oddRef s‖ ≤
        positiveBoxAnchorUpperValue
  cut_bound :
    ∀ ⦃s : ℂ⦄, s ∈ positiveBox →
      ‖positiveBoxOddRefCutVec
          data.oddRef positiveBoxK positiveBoxM s‖ ≤
        positiveBoxCutUpperValue
  sector_lower :
    ∀ ⦃s : ℂ⦄, s ∈ positiveBox →
      positiveBoxSectorLowerValue ≤ ‖verticalQuartetPrefix (q s)‖

/-- The abstract odd-reference vertical residual is bounded by anchor and cut data. -/
theorem PositiveBoxOddRefBridgeBounds.verticalResidual_bound
    {data : GenuineOddContinuationData}
    (bounds : PositiveBoxOddRefBridgeBounds data)
    {s : ℂ} (hs : s ∈ positiveBox) :
    ‖positiveBoxOddRefVerticalResidual
        data.oddRef positiveBoxK positiveBoxM s‖ ≤
      positiveBoxAnchorUpperValue + positiveBoxCutUpperValue := by
  rw [positiveBoxOddRefVerticalResidual_eq_vSplit]
  unfold positiveBoxOddRefVSplit
  exact le_trans (norm_add_le _ _)
    (add_le_add (bounds.anchor_bound hs) (bounds.cut_bound hs))

/-- Bridge-level result connecting scalar dominance and the genuine model target. -/
structure PositiveBoxOddRefBridgeResult
    (data : GenuineOddContinuationData) (s : ℂ) : Prop where
  sector_dominance :
    PositiveBoxOddRefSectorResidualDominance data.oddRef s
  true_prefix_residual :
    c2ExpandedQuartetResidualUpper
        (vSplitTiltOddRefQRatio
          data.oddRef positiveBoxN positiveBoxAnchorUpper
          positiveBoxCutUpper)
        unitScale
        (oddRefCoreHorizontalAmplitudeQRatio data.oddRef positiveBoxN)
        unitScale qNormHorizontalRatio
        positiveBoxCutUpper unitScale s <
      ‖c2QuartetBulkK2 s * verticalQuartetPrefix (q s)‖ -
        c2QuartetVerticalTailUpper s
  vertical_residual_bound :
    ‖positiveBoxOddRefVerticalResidual
        data.oddRef positiveBoxK positiveBoxM s‖ ≤
      positiveBoxAnchorUpperValue + positiveBoxCutUpperValue
  bulk_eq_genuine :
    positiveBoxOddRefBulkModel
        data.oddRef positiveBoxN positiveBoxK positiveBoxM s =
      genuineFInfinite s

/-- Conditional transport from odd-reference data to the bridge result. -/
theorem positiveBox_oddRef_bridge_result
    {data : GenuineOddContinuationData}
    (compat : PositiveBoxOddRefCompatibility data)
    (bounds : PositiveBoxOddRefBridgeBounds data)
    {s : ℂ} (hs : s ∈ positiveBox) :
    PositiveBoxOddRefBridgeResult data s := by
  have hledger :
      vSplitResidualLedgerOddRefQRatio
          data.oddRef positiveBoxN positiveBoxAnchorUpper
          positiveBoxCutUpper s <
        c2ExpandedQuartetSectorResidualMargin
          positiveBoxSectorLower s :=
    positiveBox_ledger_strict_ofOddRefTruncation
      bounds.truncation hs
  have hsector :
      PositiveBoxOddRefSectorResidualDominance data.oddRef s := by
    unfold PositiveBoxOddRefSectorResidualDominance
      C2ExpandedQuartetSectorResidualDominance
    change
      vSplitResidualUpperOddRefQRatio
          data.oddRef positiveBoxN positiveBoxAnchorUpper
          positiveBoxCutUpper s <
        c2ExpandedQuartetSectorResidualMargin
          positiveBoxSectorLower s
    rw [vSplitResidualUpperOddRefQRatio_eq_ledger]
    exact hledger
  have htrue :
      c2ExpandedQuartetResidualUpper
          (vSplitTiltOddRefQRatio
            data.oddRef positiveBoxN positiveBoxAnchorUpper
            positiveBoxCutUpper)
          unitScale
          (oddRefCoreHorizontalAmplitudeQRatio data.oddRef positiveBoxN)
          unitScale qNormHorizontalRatio
          positiveBoxCutUpper unitScale s <
        ‖c2QuartetBulkK2 s * verticalQuartetPrefix (q s)‖ -
          c2QuartetVerticalTailUpper s :=
    truePrefixResidualDominance_of_sectorResidualDominance
      (by
        unfold QuartetPrefixSectorLower positiveBoxSectorLower
        exact bounds.sector_lower hs)
      hsector
  exact {
    sector_dominance := hsector
    true_prefix_residual := htrue
    vertical_residual_bound := bounds.verticalResidual_bound hs
    bulk_eq_genuine := positiveBoxOddRefBulkModel_eq_genuine_of_compat
      compat hs
  }

end

end ContinuedQuartetAudit
end C2
