import LeanC2.PeerReview

#print C2.PeerReview.ContinuationTerminalCertificate
#check C2.PeerReview.riemannHypothesis_of_continuationTerminalCertificate
#print axioms C2.PeerReview.riemannHypothesis_of_continuationTerminalCertificate

